#cloud-config
package_update: true
package_upgrade: false
runcmd:
  - apt-get update
  - apt-get install -y fontconfig openjdk-17-jre gnupg curl apt-transport-https ca-certificates
  - rm -f /usr/share/keyrings/jenkins-keyring.gpg /usr/share/keyrings/jenkins-keyring.asc /etc/apt/sources.list.d/jenkins.list || true
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - apt-get update
  - apt-get install -y jenkins
  - systemctl enable --now jenkins
  - systemctl status jenkins --no-pager || true