#cloud-config
package_update: true
package_upgrade: false
runcmd:
  - apt-get update
  - apt-get install -y openjdk-17-jre gnupg apt-transport-https ca-certificates curl docker.io
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - apt-get update
  - apt-get install -y jenkins
  - usermod -aG docker jenkins
  - systemctl enable docker
  - systemctl enable jenkins
  - systemctl restart docker
  - systemctl restart jenkins